#tasks:
#  - name: Setup & Build
#    before: yarn global add express
#    init: yarn install
#    command: bash ./.scripts/setup.bash stable

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - lf-lang.vscode-lingua-franca